name: pfe
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  url_launcher: ^6.3.1
  mailer: ^6.4.1
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.2.4
  email_validator: ^3.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.1.0
  intl: ^0.20.2
  foundation: ^0.0.5
  cloud_functions: ^5.4.0
  fl_chart: ^0.65.0
  flutter_rating_bar: ^4.0.1
  firebase_database: ^11.3.5
  tflite_flutter: ^0.11.0
  webview_flutter: ^4.10.0
  camera: ^0.11.1
  web_socket_channel: ^3.0.2
  firebase_messaging: ^15.2.5
  http: ^1.3.0
  overlay_support: ^2.1.0
  smooth_page_indicator: ^1.2.1
  rxdart: ^0.28.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/fire_logo.png

  uses-material-design: true

impeller:
  enabled: false