// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iG-RlkFKRxNgOXUi4TM2O75m3medD7o',
    appId: '1:183744816903:web:558158557e2c1c7890c7a2',
    messagingSenderId: '183744816903',
    projectId: 'projet-fin-d-etudes-fe6a7',
    authDomain: 'projet-fin-d-etudes-fe6a7.firebaseapp.com',
    storageBucket: 'projet-fin-d-etudes-fe6a7.firebasestorage.app',
    measurementId: 'G-Y1XDC32S7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlaIUINPB2PnUPlFXo_NnIkVHKeX1UTg',
    appId: '1:183744816903:android:c53d8875d38311fe90c7a2',
    messagingSenderId: '183744816903',
    projectId: 'projet-fin-d-etudes-fe6a7',
    storageBucket: 'projet-fin-d-etudes-fe6a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjwf6y-QOlkciNQN583ZXoyD-0Gl2Q5M',
    appId: '1:183744816903:ios:a025fbc5667a244790c7a2',
    messagingSenderId: '183744816903',
    projectId: 'projet-fin-d-etudes-fe6a7',
    storageBucket: 'projet-fin-d-etudes-fe6a7.firebasestorage.app',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjwf6y-QOlkciNQN583ZXoyD-0Gl2Q5M',
    appId: '1:183744816903:ios:a025fbc5667a244790c7a2',
    messagingSenderId: '183744816903',
    projectId: 'projet-fin-d-etudes-fe6a7',
    storageBucket: 'projet-fin-d-etudes-fe6a7.firebasestorage.app',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iG-RlkFKRxNgOXUi4TM2O75m3medD7o',
    appId: '1:183744816903:web:b3e55a6c0ec370be90c7a2',
    messagingSenderId: '183744816903',
    projectId: 'projet-fin-d-etudes-fe6a7',
    authDomain: 'projet-fin-d-etudes-fe6a7.firebaseapp.com',
    storageBucket: 'projet-fin-d-etudes-fe6a7.firebasestorage.app',
    measurementId: 'G-7W9PS4BJZL',
  );

}